#!/usr/bin/env bash

# Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

mkdir ~/personal
cd ~/personal || exit

git clone https://github.com/sai-koushik-macha/ansible.git
