- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
    neovim: "{{ lookup('env', 'HOME') }}/neovim"
    user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/multimedia.yml
    - import_tasks: tasks/system_resource_tools.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/node-packages.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/python_modules.yml
    - import_tasks: tasks/debugger.yml
    - import_tasks: tasks/kvm.yml
