- name: install tmux, tree, git, fzf, xclip
  become: true
  apt:
    name: ["git", "tmux", "tree", "fzf", "xclip"]
  tags:
    - install

- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags: &tags_for_core ["install", "core"]

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags: *tags_for_core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
        "wget",
        "jq",
        "curl",
        "golang",
        "lsof",
        "ccache",
        "ninja-build",
        "moreutils",
      ]
  tags: *tags_for_core

- name: install window manager and kitty
  become: true
  apt:
    name: ["i3", "feh", "compton", "kitty", "suckless-tools"]
  tags: &tags_for_wm ["install", "i3", "kitty", "fonts"]

- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    state: directory
  tags: *tags_for_wm

- name: Dowload Go Mono Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Go-Mono.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/"
    remote_src: yes
  tags: *tags_for_wm

- name: set kitty as terminal
  lineinfile:
    dest: "{{ profile }}"
    regexp: "TERMINAL"
    line: "export TERMINAL=kitty"
  tags: *tags_for_wm

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11",  "clangd", "clangd-11"]
  tags:
    - install
    - core
    - lsp

- name: Install the language servers
  become: true
  apt:
    name: ["clang-format", "clangd", "shellcheck"]
  tags:
    - null_ls

- name: create the personal directory
  file:
    dest: "{{ personal }}"
    mode: 0775
    state: directory
  tags:
    - dev_directories

- name: create the work directory
  file:
    dest: "{{ work }}"
    mode: 0775
    state: directory
  tags:
    - dev_directories

- name: download anime repository
  ansible.builtin.git:
    repo: "git@github.com:sai-koushik-macha/anime.git"
    dest: "{{ personal }}/anime"
    depth: 1
    update: yes
  tags:
    - anime

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - rust

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: set cargo path
  shell: ". $HOME/.cargo/env"
  tags:
    - rust

- name: install stylua
  shell: ". $HOME/.cargo/env && cargo install stylua"
  tags:
    - null_ls
    - rust
