- name: install tmux, tree, git, fzf, xclip
  become: true
  apt:
    name: ["git", "tmux", "tree", "fzf", "xclip"]
  tags:
    - install

- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
        "wget",
        "jq",
        "curl",
        "golang",
        "lsof",
        "ccache",
        "ninja-build",
        "moreutils",
      ]
  tags:
    - install
    - core

- name: install window manager and kitty
  become: true
  apt:
    name: ["i3", "feh", "compton", "kitty", "suckless-tools"]
  tags:
    - i3
    - kitty

- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    state: directory
  tags:
    - fonts

- name: Dowload Go Mono Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Go-Mono.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/"
    remote_src: yes
  tags:
    - fonts

- name: set kitty as terminal
  shell: grep "export TERMINAL=kitty" ~/.profile || echo "export TERMINAL=kitty" >> ~/.profile
  tags:
    - kitty

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]
  tags:
    - install
    - core
    - lsp

- name: Install the language servers
  become: true
  apt:
    name: ["clang-format", "clangd", "shellcheck"]
  tags:
    - null_ls

- name: create the personal directory
  file:
    dest: "{{ personal }}"
    mode: 0775
    state: directory
  tags:
    - dev_directories

- name: create the work directory
  file:
    dest: "{{ work }}"
    mode: 0775
    state: directory
  tags:
    - dev_directories

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - rust

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: set cargo path
  shell: export "$HOME/.cargo/env"
  tags:
    - rust
