- name: install docker dependencies
  become: true
  apt:
    name: ["ca-certificates", "curl", "gnupg", "lsb-release"]
  tags:
    - docker

- name: add docker official gpg key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  tags:
    - docker

- name: add docker ppa
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - docker

- name: install docker
  become: true
  apt:
    update_cache: yes
    name:
      ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
  tags:
    - docker

- name: create a new group docker
  become: true
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750
  tags:
    - docker

- name: add user to the docker group
  become: true
  ansible.builtin.user:
    name: sai
    groups: docker
    append: yes
  tags:
    - docker
