- name: Remove Installed fonts
  shell: rm -rf {{ lookup('env', 'HOME') }}/.fonts
  tags:
    - fonts

- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory
  tags:
    - fonts

- name: Download Go Fonts Repo
  ansible.builtin.git:
    repo: https://go.googlesource.com/image
    dest: "{{ lookup('env', 'HOME') }}/image/"
  tags:
    - fonts

- name: Move them the fonts directory
  shell: cd {{ lookup('env', 'HOME') }}/image/font/gofont/ttfs && mv Go-* {{ lookup('env', 'HOME') }}/.fonts
  tags:
    - fonts

- name: Remove the image Repo
  shell: rm -rf {{ lookup('env', 'HOME') }}/image
  tags:
    - fonts
