- name: Install all the needed packages for kvm
  become: true
  apt:
    name:
      [
        "qemu-kvm",
        "libvirt-clients",
        "libvirt-daemon-system",
        "bridge-utils",
        "virtinst",
        "libvirt-daemon",
        "virt-manager",
      ]

  tags:
    - kvm

- name: Start the libvirt
  become: true
  ansible.builtin.systemd:
    name: libvirtd
    state: started
  tags:
    - kvm

- name: Enable the libvirt
  become: true
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
  tags:
    - kvm

- name: Add user to the libvirt group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: libvirt
    append: yes
  tags:
    - kvm

- name: Add user to the libvirt-qemu group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: libvirt-qemu
    append: yes
  tags:
    - kvm
