- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags: &tags_for_node ["install", "node"]

- name: npmjs prefix
  file:
    dest: "{{ home }}/.local/.npm-global"
    mode: 0775
    state: directory
  tags: *tags_for_node

- name: add npmjs to path
  lineinfile:
    dest: "{{ profile }}"
    regexp: ".npm"
    line: "export PATH=~/.local/.npm-global/bin:$PATH"
  tags: *tags_for_node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags: *tags_for_node

- name: Install N
  npm:
    name: n
    global: yes
  tags: *tags_for_node

- name: Set n place
  lineinfile:
    dest: "{{ profile }}"
    regexp: "N_PREFIX"
    line: export N_PREFIX="$HOME/.local/n"
  tags: *tags_for_node

- name: Install correct version of Node
  shell: ". {{ profile }} && n 16"
  tags: *tags_for_node
