- name: Install Yarn
  npm:
    name: yarn
    state: latest
    global: yes
  tags:
    - install
    - node
    - yarn

- name: install nodemon
  npm:
    name: nodemon
    state: latest
    global: yes
  tags:
    - install
    - node
    - nodemon

- name: Install Typescript
  npm:
    name: typescript
    state: latest
    global: yes
  tags:
    - install
    - node
    - typescript

- name: install eslint
  npm:
    name: eslint
    state: latest
    global: yes
  tags:
    - node
    - null_ls
