- name: Install Python
  become: true
  apt:
    name: ["python3", "python3-pip", "python3-venv"]
  tags: &tags_for_python ["install", "python", "virtualenv"]

- name: Install virtualenv
  pip:
    name: virtualenv
  tags: *tags_for_python

- name: Install pipx
  pip:
    name: pipx
  tags: *tags_for_python

- name: install pylsp
  shell: pipx install 'python-lsp-server[all]' --force
  tags: *tags_for_python
