- name: zsh setup
  become: true
  apt:
    name: ["zsh"]
  tags:
    - zsh

- name: change user shell to zsh
  become: true
  shell: usermod --shell $(which zsh) {{ user }}
  tags:
    - zsh

- name: Remove ohmyzsh if present
  file:
    dest: "{{ zsh_plugins }}"
    state: absent
  tags:
    - zsh

- name: Clone oh-my-zsh
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ zsh_plugins }}"
    depth: 1
    update: yes
  tags:
    - zsh

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ zsh_plugins }}/custom/plugins/zsh-syntax-highlighting"
    depth: 1
    update: yes
  tags:
    - zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ zsh_plugins }}/custom/plugins/zsh-autosuggestions"
    depth: 1
    update: yes
  tags:
    - zsh

- name: Install powerlevel10k
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ zsh_plugins }}/custom/themes/powerlevel10k"
    depth: 1
    update: yes
  tags:
    - zsh
