- name: zsh setup
  become: true
  apt:
    name: ["zsh"]
  tags:
    - zsh

- name: change user shell to zsh
  become: true
  shell: usermod --shell $(which zsh) {{ user }}
  tags:
    - zsh

- name: Create a directory for zsh
  file:
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh"
    mode: 0700
    state: directory
  tags:
    - zsh

- name: Download zplug
  ansible.builtin.git:
    repo: "https://github.com/zplug/zplug.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh/zplug"
    depth: 1
    update: yes
  tags:
    - zsh
