- name: zsh setup
  become: true
  apt:
    name: ["zsh"]
  tags:
    - zsh

- name: change user shell to zsh
  become: true
  shell: usermod --shell $(which zsh) {{ user }}
  tags:
    - zsh

- name: Create a directory for zsh
  file:
    dest: "{{ zsh_plugins }}"
    mode: 0700
    state: directory
  tags:
    - zsh

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ zsh_plugins }}/zsh-syntax-highlighting"
    depth: 1
    update: yes
  tags:
    - zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ zsh_plugins }}/zsh-autosuggestions"
    depth: 1
    update: yes
  tags:
    - zsh

- name: Install Powerlevel10k
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ zsh_plugins }}/powerlevel10k"
    depth: 1
    update: yes
  tags:
    - zsh
